### PR TITLE
Fix documentation quickstart example

### PR DESCRIPTION
**Pull request by pokoli**
As explained on https://github.com/C4ptainCrunch/ics.py/issues/261 here is the fix of the quickstart example to match the latest ics version.

### CODE REVIEW

**Comment by N-Coder** [comment]
It guess it might be faster to use `writelines` as shown [here](https://github.com/C4ptainCrunch/ics.py/blob/080d2cfd616718a9d549a8b90bc52ae4b337eeb9/ics/icalendar.py#L92). Additionally, the behaviour of `__str__` will change with the upcoming version 0.8, see #240. So I wouldn't merge this into master, but we could merge this into `version-0.7` if we ever do a 0.7.1 Bugfix release.

**Comment by pokoli** [comment]
Hi @N-Coder,

Thanks for your fast reply. 

I updated the PR to use `writelines` instead of writing the string. 

Do you want me to rebase this PR on version-0.7?

**Review by aureooms — APPROVED** [review]

**Comment by N-Coder** [comment]
> Do you want me to rebase this PR on version-0.7?

Yes, please do so.

**Comment by pokoli** [comment]
I've created a https://github.com/C4ptainCrunch/ics.py/pull/263 which targets the `version-0.7` branch

**Pull request closed without merging**
