### PR TITLE
Fix for leading multiple whitespace (both spaces and tabs) on a conti…

### PR DESCRIPTION
**Pull request by pcoueffin**
…nued line.

### CODE REVIEW

**Comment by C4ptainCrunch** [comment]
I don't think tabs are valid whitespace in front of a line in an ics file (i'll check). If not, we should at least output a warning.
Could you do a separated pull request for the ´categories´ bit ? (it lacks tests and it would be nice to use a list instead)

**Comment by pcoueffin** [comment]
OK.  I got a file with leading tabs from Google calendar.  Did not check
the rfc.

I'll break out the categories separately.

**Comment by pcoueffin** [comment]
Checked rfc.  I got it half right...

That is, a long line can be split between any two characters by inserting a
CRLF immediately followed by a single linear white-space character (i.e.,
SPACE or HTAB).

I'll go back to not using lstrip...

**Comment by d-k-c** [comment]
Any progress on this issue? I get bitten by it quite often with invitations generated by Outlook 14.0

**Comment by C4ptainCrunch** [comment]
I'm closing this as the PR does not follow the RFC and i don't have any example that shows a bug in the parsing. If you do have one, please open an issue with the example attached :)

**Pull request closed without merging**
