### PR TITLE
Support for VALARM

### PR DESCRIPTION
**Pull request by rkeilty**
Support for VALARM per RFC5545 specifications - http://icalendar.org/iCalendar-RFC-5545/3-6-6-alarm-component.html

### CODE REVIEW

**Comment by C4ptainCrunch** [comment]
Wow, awesome !
I'm quite in a rush right now but i'll check it very soon :)

**Comment by rkeilty** [comment]
No problem, hope this helps.  I had been working on a project that needed this support and figured it would be nice to add to your library.  Let me know if you have any questions.

**Comment by rkeilty** [comment]
Also added one more class in here, support for `AudioAlarms` in addition to `DisplayAlarms`.  TODO is `EmailAlarms`, but there should be enough there for others to add that support if they have time.

**Comment by rkeilty** [comment]
Let me know if you need any more information on this PR.

**Comment by C4ptainCrunch** [comment]
I finally had some spare time to check you pull request, sorry for the **huge** delay :/ (i had a lot of projects and exams for the uni)

The code is very nice, well tested and seems to work, thank you very much !

**Pull request merged**
