### PR TITLE
Add an event component RRULE

### PR DESCRIPTION
**Pull request by timfaner**

### CODE REVIEW

**Comment by jdeluyck** [comment]
Is there any chance this might get merged?

**Comment by C4ptainCrunch** [comment]
Hey @jdeluyck, thanks you for submitting your PR :)
There is of course some chance that it can be merged.
Could you maybe just write a test and a line of documentation ?

**Comment by lengthmin** [comment]
I will pull a new request for this pr, and keep the original commit, add some docstring.
and I think it only need write little test cases, because it is exactly the same as what you inputed.

**Comment by C4ptainCrunch** [comment]
Closing this in favor of #180

**Pull request closed without merging**
