### PR TITLE
Restructure documentation

### PR DESCRIPTION
**Pull request by tomschr**
This PR is a first draft for issue #220. It contains the following changes:

* Create subdirectories for the four types howtos, tutorials, explanation, and reference.
* Separate/sort existing documentation into these sub dirs.
* If necessary, adapt title, split files to better fit into the structure.

------

Marked it as "draft" for the time being as it's not finished and only the skeleton for our future documentation. It's also to make sure the structure is good enough before I move on and add more content.

Some changes may seem radical. I'm sure there are probably better ways how to structure it, but it's a start so we can discuss the pros and cons. I'm sure we can improve it together! :smiley: 

There are still a lot of work to do:

* I haven't found a good place for the `advanced.rst` file. Probably it needs to be rewritten and can be integrated into a tutorial, I'm not sure... :thinking: 
* Speaking of tutorials, I haven't included one yet. If we have a clearer picture of **if** and **how** this will work, we can add them later.
* There are a lot of files and sections which can (and should be!) extended. I assume, we don't have to do it with one pull request, so we can gradually move on, if you think this structure is useful.
* The API contains a warning: `autodoc: failed to import class 'parse.Container' from module 'ics'; the following exception was raised: No module named 'ics.parse'` and `Duplicate explicit target name: "github thread"`.  I leave that to someone else to fix it. :wink: 

<details>
  <summary>Screenshot (click me to show)</summary>

  ics py-doc

</details>

@C4ptainCrunch @N-Coder So what do you think? Could that work as a start? Anything you like/dislike? Let me know! :+1:

### CODE REVIEW

**Comment by C4ptainCrunch** [comment]
It looks like a good start to me :+1:

**Comment by tomschr** [comment]
@N-Coder Niko, you've showed an interest of having a section regarding the ICS format. I've added a placeholder file (see `doc/explanation/icalender-format.rst`) with a comment.

I'm not very familiar with ICS, but I would be willing to review and comment it if you would like to provide some text. Wanna try? :wink:

**Comment by tomschr** [comment]
I've moved one file into another category (`contributing.rst`), but most of it is ready to review. The rest is the same (structure-wise). Nikita seemed to like it. :wink: 

Of course it is not really finished. As I'm not sure what else I can provide, I think it's time to decide if we want to publish it as the current state and improve it step-by-step, **or** we want to do some more modifications in this PR. If you like, I can squash the commits into one if you prefer it that way.

@C4ptainCrunch what do you like?

**Comment by C4ptainCrunch** [comment]
I mirrored your branch on this repo (the branch is named `pr/223`) so that ReadTheDocs can grab it. This means you can now preview your changes over there : https://icspy.readthedocs.io/en/pr-223/

Also, as we just released ics.py 0.7, i merged master into (the mirror of) your branch. You might want to pull that into yours :)

**Comment by C4ptainCrunch** [comment]
It also seems like the reorg broke some links and footnotes.
Here are the errors i get while building on my machine:

```
WARNING: autodoc: failed to import class 'parse.Container' from module 'ics'; the following exception was raised:
No module named 'ics.parse'
WARNING: autodoc: failed to import class 'parse.ContentLine' from module 'ics'; the following exception was raised:
No module named 'ics.parse'
ics.py/doc/explanation/howto.rst:2: WARNING: Duplicate explicit target name: "github thread".
ics.py/doc/explanation/limitations.rst:45: WARNING: Too many autonumbered footnote references: only 0 corresponding footnotes available.
ics.py/doc/explanation/limitations.rst:45: WARNING: Unknown target name: "malformed".
ics.py/doc/explanation/limitations.rst:51: WARNING: Unknown target name: "errors".

```

**Comment by C4ptainCrunch** [comment]
Small other comment : things like `Create a ICS File with Thunderbird` seem weird to have in the side menu (maybe also because the title is long). We should find a way to make it prettier :)

image

**Comment by tomschr** [comment]
@C4ptainCrunch 
> It also seems like the reorg broke some links and footnotes.
> Here are the errors i get while building on my machine:

Thanks for the hint, but I get the same warnings in master too. :wink: That's why I assume, It's not caused by my reorganization of the doc.


> Small other comment : things like `Create a ICS File with Thunderbird` seem weird to have in the side menu (maybe also because the title is long). We should find a way to make it prettier :)

I can abbreviate it and remove the "with Thunderbird" part. That's easy to fix.

However, just as a more general note, it will loose clarity and you can get into the same issue again when having a longer title. IMHO, this is not a documentation issue, but a layout issue. :wink:

**Comment by C4ptainCrunch** [comment]
Ok, let's go ! I'm merging this too if it's ok to you then we can iterate again with smaller PR on master :)

**Comment by tomschr** [comment]
@C4ptainCrunch Yes, please do. We can improve it in other PRs step-by-step. Thanks! :+1:

**Pull request merged**
