### PR TITLE
Improving events arithmetics

### PR DESCRIPTION
**Pull request by guyzmo**
- added starts_within and ends_within methods
- added intersects method (aliased to `__xor__`)
- added includes method (aliased to `__in__`)
- updated operators to support datetime other parameter
- fixed missing type enforcement

### CODE REVIEW

**Comment by guyzmo** [comment]
I have yet to update tests (I already have a bunch written, but I need to adapt to your unittest framework).

**Comment by guyzmo** [comment]
but before I update tests (and fix missing stuff), please comment on the PR code ;)

**Comment by C4ptainCrunch** [comment]
I like it ! Thanks for the pr :)
Maybe  we should advertise the "magic" methods in the documentation, what do you thinks ?

**Comment by guyzmo** [comment]
ah! I got an updated version of the code, with some pydoc and tests in my workspace. I'll push that soon ☺

**Comment by C4ptainCrunch** [comment]
Moved to #110, sorry for the lag and thank you for the code !

**Comment by guyzmo** [comment]
lol, that's quite a lag ;-) I even forgot I wrote that 😆 

don't worry, we all got busy life, and I won't blame anyone for taking time to merge stuff in :)

Thank you for the project!

**Pull request closed without merging**
