### PR TITLE
Add TRANSP attribute support

### PR DESCRIPTION
**Pull request by GMLudo**
Hi,

This PR adds TRANSP attribute support: http://www.kanzaki.com/docs/ical/transp.html
I need this attribute to know if it's a free or busy event.

Thanks for your remarks.

Have a nice day.

### CODE REVIEW

**Comment by C4ptainCrunch** [comment]
Hi !

Thanks for your PR :)
I think we should consider renaming the attribute because `.transp` is not very obvious for someone who hasn't read the RFC. 
Also, since the `TRANSP` prop can take only 2 values, why not cast it to a boolean ? 
I suggest naming it `.transparent` with `TRANSPARENT` casted to `True` and `OPAQUE` to `False` with a default value of `False` (or we could do it the other way around with a property named `opaque` but it might be misleading for the ones that have read the RFC)

What do you think ?

**Comment by GMLudo** [comment]
Hi @C4ptainCrunch,

Your suggestions make sense, I've made a new commit based on your idea.
Is it ok to you ?

Have a nice day.

**Comment by GMLudo** [comment]
Gentle ping ;-)

**Comment by C4ptainCrunch** [comment]
Sorry, didn't have time to check before, i had an examination today /o\

The `TRANSP` prop has a default value, why should we bother with a `None` ?

**Comment by GMLudo** [comment]
Last remark implemented.

Ok to you ?

**Comment by C4ptainCrunch** [comment]
Looks great, thank you very much !

**Comment by C4ptainCrunch** [comment]
Do you need this feature right now ? I could do a release on pypi if you want to ;)
Or we could wait for #64 to be merged but it's a big piece so it might take a while...

**Comment by GMLudo** [comment]
I'm not in emergency, for now, I use directly my branch via pip install -e git+... ;-)

**Pull request merged**
