### PR TITLE
Release version 0.7

### PR DESCRIPTION
**Pull request by C4ptainCrunch**
See [milestone](https://github.com/C4ptainCrunch/ics.py/milestone/7) for progress.

### CODE REVIEW

**Comment by C4ptainCrunch** [comment]
It looks like apart from the Tatsu/Python3.8 issues that are going to be closed the milestone is finished :)

@N-Coder: do you wish to add more fixes in 0.7 or should we freeze and prepare the release ?

**Comment by N-Coder** [comment]
Yes! I checked all remaining issues (which now fit onto a single page) and my notes in the PR and everything should be good to go. Please also make a commit for starting `0.8dev` so that I can rebase my PR and then focus on getting it to a working state.

**Comment by C4ptainCrunch** [comment]
Perfect :ok_hand: 
I'm releasing 0.7 in less than an hour and will ping you when `0.8dev` is ready.
Thanks again for your excellent work :heart_eyes:

**Comment by C4ptainCrunch** [comment]
[0.7 is released](https://pypi.org/project/ics/0.7/) and 0.8-dev is started in  93e7858 ! :tada:

**Comment by C4ptainCrunch** [comment]
Docs are released too : https://icspy.readthedocs.io/en/v0.7/

**Pull request merged**
