### PR TITLE
feature: implement event geo

### PR DESCRIPTION
**Pull request by johnnoone**

### CODE REVIEW

**Comment by C4ptainCrunch** [comment]
Hi !

Thank you for submitting a PR :)
It seems that you still have some problems in the unit tests, could you fix them ?

I would prefer the full length `latitude` and `longitude` instead of `lat` and `lon`, `lng`, `long`. Could you change that ?

Also, it would be great if you could write a little bit of documentation :)

**Comment by pedromorgan** [comment]
Please `lat,lon`, not full length!

**Comment by C4ptainCrunch** [comment]
I understand that you don't want to type extra characters but everybody has an autocomplete nowadays.

Besides that, you just made my point, the PR uses `lng` and you asked for `lon` : there is only one way to write the long form but many ways to write the short form so people make mistakes with the short form.

**Comment by pedromorgan** [comment]
I don't care what the short version is, its much easier that the long version !

**Pull request closed without merging**
