### PR TITLE
Support ATTENDEE and ORGANIZER

### PR DESCRIPTION
**Pull request by danieltellez**
This is working for me to add atttendees to events.
It has no support on extract yet.

### CODE REVIEW

**Comment by danieltellez** [comment]
@C4ptainCrunch I've added support for ORGANIZER

**Comment by C4ptainCrunch** [comment]
cc #138

**Comment by danieltellez** [comment]
@C4ptainCrunch sorry in advance for my ignorance: Do I need to do something else to make it happen? Count on me on anything needed.

**Comment by C4ptainCrunch** [comment]
Hi @danieltellez 
Thank you for your PR ! I'm really sorry i stalled it for so long :/
I'm fixing the conflict and i'm merging this :)

**Pull request merged**
